name: Check Release
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents:
    write

jobs:
  check_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [check_release, link_check]
    steps:
      - name: Check Release
        if: ${{ matrix.group == 'check_release' }}
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Links
        if: ${{ matrix.group == 'link_check' }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-links@v1
